#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
PROCESS_NAME="spamassassin"

if [ ! -f "/tmp/.container/container-restart" ] ; then
    spamassassin_bootstrap_filesystem
    create_logrotate spamassassin "${LOG_PATH}"/"${LOG_FILE}" spamassassin spamassassin

    if [ ! -f "${CONFIG_PATH}"/local.cf ] ; then
    	print_notice "First time Install Detected - Copying Default Configuration"
    	cp -R /assets/spamassassin/* ${CONFIG_PATH}
    	chown -R spamassassin:spamassassin ${CONFIG_PATH}
    fi

    if var_true "${ENABLE_UPDATES}" ; then
    	print_notice "Enabling Automatic Ruleset Updates"
    	echo "${UPDATE_PERIOD} s6-envuidgid spamassassin sa-update && s6-svc -s HUP -h /var/run/s6/legacy-services/10-spamassassin >/dev/null 2>&1" >> /assets/cron/spamassassin
    fi

    print_notice "Updating Rulesets"
    s6-envuidgid spamassassin sa-update
fi

liftoff
